service: jackson-yuan-aws-lambda-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  countItemsInS3Bucket:
    handler: index.countItemsInS3Bucket
    name: count-items-in-s3-bucket

